# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cftunn < Formula
  desc "CLI to simplify Cloudflare Tunnel creation"
  homepage "https://github.com/thatjuan/cftunn"
  version "0.6.0"
  license "MIT"

  depends_on "cloudflared"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thatjuan/cftunn/releases/download/v0.6.0/cftunn_Darwin_x86_64.tar.gz"
      sha256 "973ffe4249a592e9dbea2ca4f44b66481386974199863d6c9826702753d2951a"

      define_method(:install) do
        bin.install "cftunn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thatjuan/cftunn/releases/download/v0.6.0/cftunn_Darwin_arm64.tar.gz"
      sha256 "f437020d1749e90c45232b342394330ec6d6708d6c0033644efa984001c655bf"

      define_method(:install) do
        bin.install "cftunn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thatjuan/cftunn/releases/download/v0.6.0/cftunn_Linux_x86_64.tar.gz"
      sha256 "1f410adb5399da2f2e2bdb7b8f495ab4b4c91b8fc20619515e3fb7ededc11782"
      define_method(:install) do
        bin.install "cftunn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thatjuan/cftunn/releases/download/v0.6.0/cftunn_Linux_arm64.tar.gz"
      sha256 "185d4a2f03981d95de01d7f9ef6f599bb0cfccd97e92eb7dc46d30389ab5f149"
      define_method(:install) do
        bin.install "cftunn"
      end
    end
  end

  test do
    system "#{bin}/cftunn", "--version"
  end
end
